from .autor_view import *
from .dash_view import *
from .editora_view import *
from .leitura_view import *
from .livro_view import *
from .usuario_view import *
from .login_view import *
from .log_view import *
from .tour_screen import *
